spring.application.name=Stripe-Processing-Service

server.port=${PORT:2222}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=mysql

spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

eureka.client.service-url.defaultZone=https://stripe-service-registry.onrender.com/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true

## Prevent premature eviction due to Render pauses / GC
eureka.instance.lease-renewal-interval-in-seconds=20
eureka.instance.lease-expiration-duration-in-seconds=180

#Actuator
management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

#Resilience

resilience4j.circuitbreaker.instances.paymentService.failure-rate-threshold=30
# Opens circuit if 50% of calls fail

resilience4j.circuitbreaker.instances.paymentService.slow-call-rate-threshold=80
# Opens circuit if 80% of calls are slow

resilience4j.circuitbreaker.instances.paymentService.slow-call-duration-threshold=5s
# A call is considered slow if it takes longer than 5 seconds

# --- Sliding Window ---
resilience4j.circuitbreaker.instances.paymentService.sliding-window-type=COUNT_BASED
# Measure based on number of calls

resilience4j.circuitbreaker.instances.paymentService.sliding-window-size=6
# Look at the last 10 calls to calculate failure rate

resilience4j.circuitbreaker.instances.paymentService.minimum-number-of-calls=3
# Need at least 5 calls before failure rate is calculated

# --- OPEN State ---
resilience4j.circuitbreaker.instances.paymentService.wait-duration-in-open-state=30s
# Stay OPEN for 30 seconds before moving to HALF_OPEN

# --- HALF_OPEN State ---
resilience4j.circuitbreaker.instances.paymentService.permitted-number-of-calls-in-half-open-state=3
# Allow 3 trial calls in HALF_OPEN to test if service recovered

resilience4j.circuitbreaker.instances.paymentService.automatic-transition-from-open-to-half-open-enabled=true
# Automatically move to HALF_OPEN after wait duration without needing a trigger

# --- Exceptions ---
resilience4j.circuitbreaker.instances.paymentService.record-exceptions[0]=feign.FeignException
resilience4j.circuitbreaker.instances.paymentService.record-exceptions[1]=java.util.concurrent.TimeoutException
# These exceptions count as failures

resilience4j.circuitbreaker.instances.paymentService.ignore-exceptions[0]=org.springframework.web.server.ResponseStatusException
# Business errors like card declined should NOT trip the circuit